_target_: src.models.timm_com.CommKD

lr: 0.001
weight_decay: 0.0005

teacher_model: 'resnet34'
student_model: 'resnet18'
num_students: 2

kd_weights:
  - [0.0, 0.1, 0.1]
  - [0.9, 0.0, 0.1]
  - [0.9, 0.9, 0.0]