_target_: src.datamodules.imagenet_datamodule.ShardImagenetData

shards:
  imagenet-train-{000000..000146}.tar

valshards:
  imagenet-val-{000000..000006}.tar

bucket:
  ${data_dir}/imagenet_shards
  
batch_size: 64
pin_memory: True
num_workers: 4